- QueryEngine/ResultSet.h
- QueryEngine/ResultSetConversion.cpp
- ThriftHandler/MapDHandler.cpp
- ThriftHandler/MapDHandler.h
- mapd.thrift
cc: @andrewseidl 
This PR is a starting point for writing the serialized Arrow buffer to host shared memory in CPU mode via [`shmget`](http://man7.org/linux/man-pages/man2/shmget.2.html). I've tested it works locally on macOS Sierra 10.12.5, though it should work on any System V platform.
My C++ fu is not strong, so I cargo-culted the ThriftHandler. I implemented new code paths to reduce the risk of introducing new bugs. I expect someone from the team will want to delete or rewrite this code to conform to the coding guidelines.
The core logic is in [`ResultSet::getArrowCopy`](https://github.com/mapd/mapd-core/compare/master...graphistry:shm-ipc#diff-3055c0b6e6034b731c9cdad3b3cd3121R529). I've added comments inline with the following questions/todos:
- I've used stdlib rand() to [generate …
> Write Arrow buffer into host shared memory in CPU mode

- CMakeLists.txt
In https://github.com/mapd/mapd-core/blob/e745367c41c8dfa28487870816cf27a57a46204d/cmake/Modules/FindArrow.cmake#L62 we set `Arrow_INCLUDE_DIRS`, but the main `CMakeLists.txt` was using `Arrow_INCLUDE_DIR`, singular. Hopefully this is the right fix (I haven't used cmake before).
Before this, I could `cmake -DCMAKE_BUILD_TYPE=debug -DENABLE_CUDA=off -DENABLE_ARROW_CONVERTER=on -DArrow_LIBRARY=~/miniconda3/envs/mapd-dev/lib/libarrow.dylib ..` fine, but my `make` failed with
```
/Users/taugspurger/sandbox/mapd-core/QueryEngine/ResultSet.h:34:10: fatal error: 'arrow/table.h' file not found
#include "arrow/table.h"
```
I don't think this closes https://github.com/mapd/mapd-core/issues/25, as now my `make` fails with
```
[ 82%] Building CXX object …
```
> cmake: Fixed arrow include directory usage

- java/mapdjdbc/src/main/java/com/mapd/jdbc/MapDPreparedStatement.java
Create statement during initialization of prepared statement rather than during query execution; implemented setter and getter functions based on statement functions; changed logging to debug rather than info.
Was getting NullPointerExceptions when trying to use the `setMaxRows` function, this resolved the issue on my end. INFO level logging was causing a communication error in one of the applications I was using, changing to debug level fixed the issue, but not sure if there's a cleaner solution to that problem.
> NullPointerException fixes in PreparedStatement

- CMakeLists.txt
- QueryEngine/ArrowResultSet.cpp
- QueryEngine/ArrowResultSet.h
- QueryEngine/ArrowUtil.cpp
- QueryEngine/ArrowUtil.h
- QueryEngine/CMakeLists.txt
- QueryEngine/ResultSet.h
- QueryEngine/ResultSetConversion.cpp
- cmake/Modules/FindArrow.cmake
- scripts/common-functions.sh
- scripts/mapd-deps-centos.sh
- scripts/mapd-deps-ubuntu.sh
* Use up-to-date Arrow IPC serialization / read APIs
* Use vector appends with Arrow builders (cf ARROW-1468)
* Avoid extra full result set memory copy in multithreaded fetches
* Use library calls for pretty printing (cf ARROW-1396)
> Migrate Arrow-related code to incorporate IPC code improvements since 0.4.x, simplifications and perf improvements

- CMakeLists.txt
- Import/Importer.cpp
- Import/Importer.h
- QueryEngine/ArrowResultSet.cpp
- QueryEngine/ArrowUtil.cpp
- QueryEngine/ArrowUtil.h
- QueryEngine/CMakeLists.txt
- QueryEngine/ResultSet.h
- QueryEngine/ResultSetConversion.cpp
- README.md
- Tests/ExecuteTest.cpp
- ThriftHandler/MapDHandler.cpp
- ThriftHandler/MapDHandler.h
- mapd.thrift
- scripts/common-functions.sh
There's some code duplication with the `load_table_binary_columnar`, but I don't have enough context about other parts of the system to know the best way to refactor. 
Some TODO
This also makes Arrow a required build dependency
Close #89
> ENH: Add RPC endpoint for loading serialized Arrow columnar payloads

- Shared/Datum.cpp
parse_numeric did not explicitly handle negative values, which would
cause the negative to be dropped if the before_dot value was `-0`.
Resolves #98
> import: fix DECIMAL import for values -1 < val < 0

- java/mapdjdbc/src/main/java/com/mapd/jdbc/MapDPreparedStatement.java
Closes #45 
To reproduce: "SELECT * FROM t WHERE id = ?"
Negative "limit" argument in String.split() prevents it from ignoring empty splits
> Fixed JDBC ignoring prepared statement parameter at the end of a query

- Analyzer/Analyzer.cpp
- Analyzer/Analyzer.h
- Parser/ParserNode.cpp
- QueryEngine/CalciteAdapter.cpp
- QueryEngine/ExpressionRewrite.cpp
- QueryEngine/GroupByAndAggregate.cpp
- QueryEngine/HyperLogLog.h
- QueryEngine/RelAlgAbstractInterpreter.cpp
- QueryEngine/RelAlgAbstractInterpreter.h
- QueryEngine/RelAlgExecutor.cpp
- QueryEngine/RelAlgOptimizer.cpp
- QueryEngine/RelAlgTranslator.cpp
- Tests/ExecuteTest.cpp
- java/calcite/src/main/java/com/mapd/calcite/parser/MapDSqlOperatorTable.java
It closes #29 
Usage: `APPROX_COUNT_DISTINCT(expr, integer_literal)`,
where `integer_literal` is the desired error rate in percents. Should be >= 1.
Internally it calculates a bitmap precision to provide the desired relative
error and uses it instead of `g_hll_precision_bits`.
> Implemented optional error percentage argument for APPROX_COUNT_DISTINCT

- QueryEngine/RelAlgExecutor.cpp
- Tests/ExecuteTest.cpp
Handle the case where nothing is left after extracting the common expression.
> Fix reverse_logical_distribution corner cases

- QueryEngine/ColumnIR.cpp
- Tests/ExecuteTest.cpp
We cannot do it when the types are different, for example because of
different dictionary encodings between the two sides. Fixes #131.
> Fix reuse of left hand side of an equi join

- Tests/ExecuteTest.cpp
The problem shows when sharding is enabled, which changes the row order.
> Fix nondeterministic test

- Analyzer/Analyzer.cpp
- Tests/ExecuteTest.cpp
BinOper::analyze_type_info must preserve nullability for both sides.
> Fix issues with operand nullability for time comparisons

- Parser/ParserNode.cpp
- Tests/ExecuteTest.cpp
Commit f2a2b5b41b7b347ed9e85be7509b2472632a9598 changed the logic to
account for dictionaries with the same encoding, but it didn't check
that the dictionaries are actually shared (same compression parameter).
> Decompress dictionary-encoded sides when encoding is different

- SQLFrontend/CMakeLists.txt
- SQLFrontend/mapdql.cpp
- Used boost::regex as requested
- Uses search instead of match mechanics, so substring searches can be applied
- Tried to clean up some repetitive constructs and provided some new functions with lambda expressions on return from thrift queries with retry
- No regex provided reverts to unfiltered output, like before
- Commit formatted with clang-format, as required
Some examples:
**Unfiltered Table Output**
> mapdql> \t
> flights_2008_7M
> test
> test_x
> test_inner_x
> bar
> test_inner
> 
**End of line match**
> mapdql> \t _x$
> test_x
> test_inner_x
**Inner match**
> mapdql> \t _inner_
> test_inner_x
> 
And it works on \u and \v as well:
**Unfiltered User Output**
> mapdql> \u
> mapd
> homer
> marge
> bart
> lisa
> lisaSimpson
> sideshowbob
> 
**Start of line match**
> mapdql> \u ^lisa …
> Implementation of feature requested in Issue#138, re: mapdql commands regex

- SQLFrontend/mapdql.cpp
Minor oversight; help string corrected.
> Minor correction - fixes missing newline at end of help message for \o

- Tests/CMakeLists.txt
- Tests/TokenCompletionHintsTest.cpp
- ThriftHandler/CMakeLists.txt
- ThriftHandler/MapDHandler.cpp
- ThriftHandler/MapDHandler.h
- ThriftHandler/TokenCompletionHints.cpp
- ThriftHandler/TokenCompletionHints.h
Calcite doesn't honor our permissions and the context-sensitive identifier
completion is brittle. Only use it for keywords, filtered by a narrow
whitelist.
> Switch to token-based completion hints

- SQLFrontend/mapdql.cpp
Changed input loop to use smart pointer with a custom deleter that invokes C-style free().   Programmer no longer needs to worry about pairing the free or has to worry about exceptions.
> Issue #167  Linenoise memory leak fix

- Shared/funcannotations.h
CUDA_VERSION is defined in the driver API only, __CUDACC_VER_MAJOR__ is
the macro for CUDA C++.
> Fix definition of STATIC_QUAL

- QueryEngine/Execute.cpp
- Tests/ExecuteTest.cpp
It can happen when a none-encoded string is projected and then an ORDER
BY on a different column is applied.
> Remove wrong check in Executor::fetchChunks

- Calcite/Calcite.cpp
- Calcite/Calcite.h
- Tests/TokenCompletionHintsTest.cpp
- ThriftHandler/MapDHandler.cpp
- ThriftHandler/MapDHandler.h
- ThriftHandler/TokenCompletionHints.cpp
- ThriftHandler/TokenCompletionHints.h
- java/calcite/src/main/java/com/mapd/calcite/parser/MapDParser.java
- java/calcite/src/main/java/com/mapd/parser/server/CalciteServerHandler.java
- java/calcite/src/main/java/org/apache/calcite/prepare/MapDPlanner.java
- java/calcite/src/main/java/org/apache/calcite/prepare/MapDSqlAdvisor.java
- java/calcite/src/main/java/org/apache/calcite/prepare/MapDSqlAdvisorValidator.java
- java/thrift/calciteserver.thrift
Bring back the Calcite-based completion with improvements. It now
follows the permissions, can auto-complete grouped columns and doesn't
conflate column and table suggestions anymore.
> Context-sensitive auto completion

- Tests/TokenCompletionHintsTest.cpp
- ThriftHandler/MapDHandler.cpp
- ThriftHandler/TokenCompletionHints.cpp
- ThriftHandler/TokenCompletionHints.h
After SELECT but before FROM, only suggest column if it's the first
token after SELECT or there's a trailing comma.
> Choose smartly between FROM keyword hint and column hints

- QueryEngine/JoinHashTable.cpp
- Tests/ExecuteTest.cpp
The fragment distribution logic must change a bit before outer joins can
be sharded. Disable for now for correctness' sake, which wasn't done for
the baseline join hash table layout (used for joins on multiple columns).
> Disable sharding for baseline outer joins as well

- Fragmenter/Fragmenter.h
- QueryEngine/Execute.cpp
- QueryEngine/GroupByAndAggregate.cpp
- QueryEngine/GroupByRuntime.cpp
- QueryEngine/InputMetadata.cpp
- QueryEngine/RelAlgExecutor.cpp
Don't store lazily fetched columns multiple times. Also cap the projection buffer size by the size of the fragment.
> Optimize single table projection queries memory usage

- QueryEngine/JoinHashTableQueryRuntime.cpp
We can stop once we hit an empty slot.
> Stop probing early in get_composite_key_index_impl

- CMakeLists.txt
- QueryRunner/CMakeLists.txt
Fixes for two misc CMake issues that have popped up recently:
- use VERSION_GREATER instead of VERSION_GREATER_EQUAL (#262)
- cmake: explicitly set Parser as dependency of QueryRunner (Quansight/mapd#20)
> CMake fixes: VERSION_GREATER, explicit Parser dependency

- java/mapdjdbc/src/main/java/com/mapd/jdbc/MapDPreparedStatement.java
Previously the generated sql was of the form:
WHERE column = "f"
which is not recognized by Calcite. Now it generates:
WHERE column = false
Resolves #274
> jdbc: generate recognized syntax when using SetBoolean

- README.md
- scripts/mapd-deps-ubuntu1604.sh
Based on #300 and #299, it appears that the dependencies should be updated. PR switches to gcc7 from 5, builds xerces 3.2.2 and configures two other libraries with `--with-boost`
> [ENH] Update to gcc6 and fix SAML deps

- QueryEngine/RelAlgAbstractInterpreter.h
- QueryEngine/RelAlgExecutor.cpp
This fixes an issue where assert failures are triggered on certain queries. If a sub query runs on gpu but the outer query fails to run on gpu due to space limitations, the whole query is retried on gpu. This then causes a few checks to fail.
> Fixing assertion failure when query falls back to cpu when a subquery ran in gpu mode

- ThirdParty/Arrow/apache-arrow.rb
Per https://github.com/OSGeo/homebrew-osgeo4mac/issues/626 and others, 
Homebrew changed its compiler toolchain such that this line causes 
errors. Removing this line allows for installation to continue.
Fixes #321
> Comment out needs : cxx11

- Import/Importer.cpp
This came up when recompiling with jemalloc. The database hung while importing from csv. I then found the issue with the address sanitizer.
> Fixing declaration of char[] buffers for csv import

- java/omniscijdbc/src/main/java/com/omnisci/jdbc/OmniSciConnection.java
- java/omniscijdbc/src/main/java/com/omnisci/jdbc/OmniSciData.java
- java/omniscijdbc/src/main/java/com/omnisci/jdbc/OmniSciDatabaseMetaData.java
This patch correct the issues #163 #164 #310 #311
Enhancements
The new implementation of the getPrimaryKey method makes the driver compatible with Tableau 2019.1
Now the GetTables method returns a list of table and views of the current database if the schemaPattern is null or it matches the current database name
> JDBC: Correction of issues and enhancements on OmniSciDatabaseMetaData class

- QueryEngine/CgenState.h
- QueryEngine/DateTimeIR.cpp
- QueryEngine/NativeCodegen.cpp
Running TPC-H benchmark queries on Omnisci we found that for some queries generated row_func functions have datetime computations (using DateAdd function call) on literals. When row_func is inlined these computations become loop invariant but are not moved out from the loop. In some cases DateAdd call leads to gmtime_r_newlib call which is quite expensive.
This patch add Loop Invariant Code Motion pass to pass manager and add function attributes for DateAdd declaration to correctly identify it as a loop invariant.
This patch gives ~3x speed-up for TPC-H queries Q5, Q10 and ~20x speed-up for Q6, Q12. Actually I could only run 11 of 22 queries of the benchmark so other queries also might be affected.
LICM pass seems to be quite useful and not expensive (it should be linear to total number …
> Add LICM pass and enable it for DateAdd call

- QueryEngine/ArithmeticIR.cpp
- QueryEngine/CodeGenerator.h
This patch utilizes arithmetic with overflow LLVM intrinsics to detect overflows/underflows. On x86 CPU this allows to use overflow bit flag instead of doing reverse operations for the check. This is especially useful for multiplication case. TPC-H query Q1 has multiplication with overflow check and this patch gives it 6.4x speed-up.
I'm not sure about implications for CUDA. Used intrinsics are not x86 specific so I expect them to work on all platforms. Unfortunately I don't have CUDA on my server to test it.
> Use arithmetic with overflow intrinsics to detect overflows

- .github/workflows/main.yml
GitHub Actions script that will build Sphinx docs in `docs` directory and push the resulting files from `docs/build/html` to the `gh-pages` branch.
A few steps are remaining before this can be merged:
- `GITHUB_WRITE_TOKEN` secret variable provided in the repo. The default Actions token does not have sufficient permissions to push.
- GitHub Pages enabled, using the `gh-pages` branch (this branch should also be protected)
> GitHub Actions script to build documentation and push to Pages

- MapDServer.cpp
so the server can be run as:
$ omnisci_server --db-query-list file.sql --exit-after-warmup
@gshimansky @fexolm
> Multi-line db-query-list file statements, added --exit-after-warmup 

- SQLFrontend/CommandFunctors.h
Clarify that the `\c` command is for switching databases as a different user.
@gshimansky pointed out that since we have a separate `\db` command for switching between databases (albeit as the same user), it would seem like `\c` might instead stand for `create`.
We should probably find a better way to combine these two commands.
> omnisql: clarify \c command help text

- QueryEngine/ColumnarResults.cpp
- QueryEngine/ResultSet.cpp
- QueryEngine/ResultSet.h
Use zero-copy column fetch from columnar result sets
> use zero-copy fetch for columnar result sets when possible

- QueryEngine/ResultSet.cpp
- QueryEngine/ResultSet.h
- QueryEngine/ResultSetIteration.cpp
This patch speeds up row count computation for projections using a binary search instead of a linear scan.
> avoid full scan in ResultSet::rowCount when possible

- QueryEngine/ArrowResultSetConverter.cpp
This patch allows to perform arrow serialization into pre-allocated shared memory. In my tests it showed 3x serialization speed-up. I also added some timers to converter.
> Serialize arrow RecordBatch directly to shared memory

- QueryEngine/JoinHashTable.cpp
- Tests/ExecuteTest.cpp
This patch allows hash table usage for equijoins with decimal columns.
> allow decimal columns in hash joins

- scripts/arch/arrow/PKGBUILD
- scripts/mapd-deps-arch.sh
Tried to run mapd-deps-arch.sh on an arch Linux and failed. This is an attempt fixing the script.
> Fix mapd-deps-arch.sh arrow install, updated arch/PKGBUILD md5sum

- CMakeLists.txt
- Embedded/setup.in.py
- Embedded/test/test_exceptions.py
- Embedded/test/test_fsi.py
- Embedded/test/test_readcsv.py
- OSDependent/Unix/omnisci_path.cpp
- QueryEngine/NativeCodegen.cpp
- python/setup.py
This PR includes:
- determine the omniscidb root path from the location of libDBEngine.so
- include a complete set of thrift files to installation
- use OMNISCI_ROOT_PATH environment variable to determine the root path for building Python omniscidbe extension module
- Python extension module `dbe` is renamed to `omniscidbe`
This PR is used in https://github.com/conda-forge/omniscidb-feedstock/pull/39 to build the following conda-forge packages:
- omniscdb-common, linux only
- omniscidb, cpu and cuda builds, linux only
- omniscidbe, cpu and cuda builds, linux only
- pyomniscidb, python versions 3.6, 3.7, 3.8, linux, windows, os
- pyomniscidbe, cpu and cuda builds, python version 3.6, 3.7, 3.8, linux only
> Support omniscidb conda-forge feedstock builds with embedding feature [Linux-only]

- Tests/CMakeLists.txt
- Tests/DBHandlerTestHelpers.h
- Tests/LoadBalancerTest.cpp
- Tests/SessionsStoreTest.cpp
- ThriftHandler/DBHandler.cpp
- ThriftHandler/DBHandler.h
This PR fixes a few issues:
Fixes persistence of num sessions.
Currently there is no distinction between the number of sessions specified by the command line and the number of sessions persisted between restarts, so we had no way of telling if the restarted value came from a cmd line parameter or a previous license and which should take priority. This is fixed by creating a new record of the number of sessions in the DBhandler so that we have a distinction between the current value, the cmd-line value, and the license value.
Signed-off-by: jack <jack@omnisci.com>
> Update system dynamically when new license is set.
